{% set name = "polyfuzz" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 6cbbdbae8c124985200049b3d79d04c7ed9dac5b6d8daa75fcd3022c1799b2ad

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - joblib >=0.14.0
    - matplotlib >=3.2.2
    - numpy >=1.18.5,<=1.19.4
    - pandas >=0.25.3
    - pip
    - python
    - rapidfuzz >=0.13.1
    - scikit-learn >=0.22.2.post1
    - scipy >=1.3.1
    - seaborn >=0.11.0
    - tqdm >=4.41.1
  run:
    - joblib >=0.14.0
    - matplotlib >=3.2.2
    - numpy >=1.18.5,<=1.19.4
    - pandas >=0.25.3
    - python
    - rapidfuzz >=0.13.1
    - scikit-learn >=0.22.2.post1
    - scipy >=1.3.1
    - seaborn >=0.11.0
    - tqdm >=4.41.1

test:
  imports:
    - polyfuzz
    - polyfuzz.datasets
    - polyfuzz.models
    - tests

about:
  home: "https://github.com/MaartenGr/PolyFuzz"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "PolyFuzz performs fuzzy string matching, grouping, and evaluation."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
