language: python
python:
  - "3.6"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --append channels conda-forge
  - conda update -q conda

  # Setup environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip
  # tokenizers tensorboardx seqeval transformers>=3.0.2 streamlit wandb
  - conda activate test-environment
  # Fixed to 3.20.5 as this version worked
  - conda install conda-build=3.20.5
  # Print info
  - conda info -a
  - conda list

script:
  # 0. Clean WS
  - rm -rf simpletransformers/
  # 1. Create the conda skeleton
  - conda skeleton pypi simpletransformers
  # 2. Run the conda-build
  ##- conda-build simpletransformers --python=3.6
  - conda-build simpletransformers
  # 3. Create packages for multiple platforms
  # - conda convert --platform all /home/travis/miniconda/envs/test-environment/conda-bld/linux-64/click-7.0-py37_0.tar.bz2 -o /home/travis/miniconda/envs/test-environment/conda-bld/all/

  
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "officerJones"
  - git config --local user.email "officerJones013@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file_glob: true
  file:
    # For conda recipe:
    - simpletransformers/*
    # In case of package:
    - /home/travis/miniconda/envs/test-environment/conda-bld/*/*
  skip_cleanup: true
  on:
    all_branches: true
