language: python
python:
  - "3.8"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --append channels conda-forge
  - conda update -q conda

  # Setup environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip conda-build tokenizers tensorboardx seqeval transformers>=3.0.2 streamlit wandb
  - conda activate test-environment

  # Print info
  - conda info -a

script:
  - conda skeleton pypi simpletransformers
  - conda-build simpletransformers
  # - conda convert --platform all /home/travis/miniconda/envs/test-environment/conda-bld/linux-64/click-7.0-py37_0.tar.bz2 -o /home/travis/miniconda/envs/test-environment/conda-bld/all/

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "officerJones"
  - git config --local user.email "officerJones013@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file_glob: true
  file:
    - meta.yaml
    - /home/travis/miniconda/envs/test-environment/conda-bld/*/*.tar.bz2
  skip_cleanup: true
  on:
    all_branches: true
